/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    categories: Category;
    projects: Project;
    services: Service;
    news: News;
    clients: Client;
    logos: Logo;
    team: Team;
    milestones: Milestone;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    logos: LogosSelect<false> | LogosSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    milestones: MilestonesSelect<false> | MilestonesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Os textos das páginas. Não se criam nem se apagam: editam-se.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  key: string;
  /**
   * Hoje só a homepage as usa: são as fotografias do topo, ao lado do título. Com mais do que uma, trocam entre si em fundido, pela ordem desta lista. Sem nenhuma, o topo mostra a capa do primeiro projeto.
   */
  images?: (number | Media)[] | null;
  entries?:
    | {
        key: string;
        pt?: string | null;
        en?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  /**
   * De onde a imagem foi migrada.
   */
  legacyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  titlePt: string;
  titleEn?: string | null;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  date: string;
  author?: string | null;
  readingMinutes?: number | null;
  category?: (number | null) | Category;
  excerpt?: {
    pt?: string | null;
    en?: string | null;
  };
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tradução do corpo. Vazio, o site em inglês mostra o texto português.
   */
  bodyEn?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lang?: ('pt' | 'en') | null;
  /**
   * Serve o redirecionamento 301.
   */
  legacyPath?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  titlePt: string;
  titleEn?: string | null;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  client: string;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  year?: string | null;
  date?: string | null;
  order?: number | null;
  /**
   * Ligado, entra na lista de casos. Desligado, fica no arquivo.
   */
  written?: boolean | null;
  subtitle?: string | null;
  disciplines?: string[] | null;
  title?: {
    pt?: string | null;
    en?: string | null;
  };
  summary?: {
    pt?: string | null;
    en?: string | null;
  };
  team?: {
    pt?: string | null;
    en?: string | null;
  };
  cover?: (number | null) | Media;
  story?:
    | (
        | {
            heading?: string | null;
            level?: ('h2' | 'h3') | null;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            images: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            /**
             * Endereço do ficheiro.
             */
            mp4?: string | null;
            webm?: string | null;
            poster?: (number | null) | Media;
            portrait?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
        | {
            label: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'link';
          }
      )[]
    | null;
  /**
   * Sem isto, a faixa de números não vai para o ecrã.
   */
  numbersValidated?: boolean | null;
  headline?: {
    /**
     * Como sai para o ecrã: +38%, 2,4x, 11 dias.
     */
    value?: string | null;
    label?: {
      pt?: string | null;
      en?: string | null;
    };
  };
  kpis?:
    | {
        /**
         * Como sai para o ecrã: +38%, 2,4x, 11 dias.
         */
        value?: string | null;
        label?: {
          pt?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  quote?: {
    text?: {
      pt?: string | null;
      en?: string | null;
    };
    author?: string | null;
    role?: {
      pt?: string | null;
      en?: string | null;
    };
  };
  legacyPath?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  namePt: string;
  nameEn?: string | null;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  order?: number | null;
  claim?: {
    pt?: string | null;
    en?: string | null;
  };
  link?: {
    pt?: string | null;
    en?: string | null;
  };
  promise?: {
    pt?: string | null;
    en?: string | null;
  };
  includes?:
    | {
        item?: {
          pt?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  phases?:
    | {
        name?: {
          pt?: string | null;
          en?: string | null;
        };
        body?: {
          pt?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  cases?: (number | Project)[] | null;
  accent?: ('lavender' | 'chartreuse' | 'coral') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  titlePt: string;
  titleEn?: string | null;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  date: string;
  kind: 'noticia' | 'evento' | 'press';
  /**
   * Só para press: onde saiu.
   */
  outlet?: string | null;
  summary?: {
    pt?: string | null;
    en?: string | null;
  };
  /**
   * Se a notícia tem artigo no site, é para lá que a linha leva.
   */
  post?: (number | null) | Post;
  /**
   * Usado quando não há artigo: notícia na imprensa, inscrição num evento.
   */
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  sector:
    | 'financeiro'
    | 'saude'
    | 'bebidas'
    | 'consumo'
    | 'retalho'
    | 'industria'
    | 'construcao'
    | 'servicos'
    | 'arte'
    | 'eventos'
    | 'lazer'
    | 'tecnologia';
  logo?: (number | null) | Media;
  /**
   * Nome da galeria a que pertence.
   */
  gallery?: string | null;
  link?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos".
 */
export interface Logo {
  id: number;
  name?: string | null;
  gallery: string;
  image: number | Media;
  link?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role?: {
    pt?: string | null;
    en?: string | null;
  };
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milestones".
 */
export interface Milestone {
  id: number;
  year: string;
  body?: {
    pt?: string | null;
    en?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'logos';
        value: number | Logo;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'milestones';
        value: number | Milestone;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  images?: T;
  entries?:
    | T
    | {
        key?: T;
        pt?: T;
        en?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  titlePt?: T;
  titleEn?: T;
  slug?: T;
  date?: T;
  author?: T;
  readingMinutes?: T;
  category?: T;
  excerpt?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  cover?: T;
  body?: T;
  bodyEn?: T;
  lang?: T;
  legacyPath?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  titlePt?: T;
  titleEn?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  client?: T;
  slug?: T;
  year?: T;
  date?: T;
  order?: T;
  written?: T;
  subtitle?: T;
  disciplines?: T;
  title?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  summary?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  team?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  cover?: T;
  story?:
    | T
    | {
        text?:
          | T
          | {
              heading?: T;
              level?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              mp4?: T;
              webm?: T;
              poster?: T;
              portrait?: T;
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              url?: T;
              id?: T;
              blockName?: T;
            };
        link?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
      };
  numbersValidated?: T;
  headline?:
    | T
    | {
        value?: T;
        label?:
          | T
          | {
              pt?: T;
              en?: T;
            };
      };
  kpis?:
    | T
    | {
        value?: T;
        label?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        id?: T;
      };
  quote?:
    | T
    | {
        text?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        author?: T;
        role?:
          | T
          | {
              pt?: T;
              en?: T;
            };
      };
  legacyPath?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  namePt?: T;
  nameEn?: T;
  slug?: T;
  order?: T;
  claim?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  link?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  promise?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  includes?:
    | T
    | {
        item?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        id?: T;
      };
  phases?:
    | T
    | {
        name?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        body?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        id?: T;
      };
  cases?: T;
  accent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  titlePt?: T;
  titleEn?: T;
  slug?: T;
  date?: T;
  kind?: T;
  outlet?: T;
  summary?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  post?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  sector?: T;
  logo?: T;
  gallery?: T;
  link?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos_select".
 */
export interface LogosSelect<T extends boolean = true> {
  name?: T;
  gallery?: T;
  image?: T;
  link?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milestones_select".
 */
export interface MilestonesSelect<T extends boolean = true> {
  year?: T;
  body?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  legacyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}