/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    categories: Category;
    projects: Project;
    services: Service;
    news: News;
    clients: Client;
    logos: Logo;
    team: Team;
    milestones: Milestone;
    messages: Message;
    departments: Department;
    'job-functions': JobFunction;
    jobs: Job;
    applications: Application;
    media: Media;
    documents: Document;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    clients: ClientsSelect<false> | ClientsSelect<true>;
    logos: LogosSelect<false> | LogosSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    milestones: MilestonesSelect<false> | MilestonesSelect<true>;
    messages: MessagesSelect<false> | MessagesSelect<true>;
    departments: DepartmentsSelect<false> | DepartmentsSelect<true>;
    'job-functions': JobFunctionsSelect<false> | JobFunctionsSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    documents: DocumentsSelect<false> | DocumentsSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Os textos das páginas. Não se criam nem se apagam: editam-se.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  key: string;
  /**
   * Hoje só a homepage as usa: são as fotografias do topo, ao lado do título. Com mais do que uma, trocam entre si em fundido, pela ordem desta lista. Sem nenhuma, o topo mostra a capa do primeiro projeto.
   */
  images?: (number | Media)[] | null;
  entries?:
    | {
        key: string;
        pt?: string | null;
        en?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Como esta imagem se chama no painel. Não vai para o site.
   */
  title?: string | null;
  alt: string;
  caption?: string | null;
  /**
   * De onde a imagem foi migrada.
   */
  legacyUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    wide?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  titlePt: string;
  titleEn?: string | null;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  /**
   * Entra no endereço em inglês (/en/…). Vazio, o inglês usa o slug português.
   */
  slugEn?: string | null;
  date: string;
  author?: string | null;
  readingMinutes?: number | null;
  category?: (number | null) | Category;
  excerpt?: {
    pt?: string | null;
    en?: string | null;
  };
  cover?: (number | null) | Media;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Tradução do corpo. Vazio, o site em inglês mostra o texto português.
   */
  bodyEn?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  lang?: ('pt' | 'en') | null;
  /**
   * Serve o redirecionamento 301.
   */
  legacyPath?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  titlePt: string;
  titleEn?: string | null;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  client: string;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  /**
   * Entra no endereço em inglês (/en/…). Vazio, o inglês usa o slug português.
   */
  slugEn?: string | null;
  year?: string | null;
  date?: string | null;
  order?: number | null;
  /**
   * Ligado, entra na lista de casos. Desligado, fica no arquivo.
   */
  written?: boolean | null;
  subtitle?: string | null;
  disciplines?: string[] | null;
  title?: {
    pt?: string | null;
    en?: string | null;
  };
  summary?: {
    pt?: string | null;
    en?: string | null;
  };
  team?: {
    pt?: string | null;
    en?: string | null;
  };
  cover?: (number | null) | Media;
  story?:
    | (
        | {
            heading?: string | null;
            level?: ('h2' | 'h3') | null;
            body?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            image: number | Media;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image';
          }
        | {
            images: (number | Media)[];
            id?: string | null;
            blockName?: string | null;
            blockType: 'gallery';
          }
        | {
            /**
             * Endereço do ficheiro.
             */
            mp4?: string | null;
            webm?: string | null;
            poster?: (number | null) | Media;
            portrait?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'video';
          }
        | {
            url: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'embed';
          }
        | {
            label: string;
            href: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'link';
          }
      )[]
    | null;
  /**
   * Sem isto, a faixa de números não vai para o ecrã.
   */
  numbersValidated?: boolean | null;
  headline?: {
    /**
     * Como sai para o ecrã: +38%, 2,4x, 11 dias.
     */
    value?: string | null;
    label?: {
      pt?: string | null;
      en?: string | null;
    };
  };
  kpis?:
    | {
        /**
         * Como sai para o ecrã: +38%, 2,4x, 11 dias.
         */
        value?: string | null;
        label?: {
          pt?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  quote?: {
    text?: {
      pt?: string | null;
      en?: string | null;
    };
    author?: string | null;
    role?: {
      pt?: string | null;
      en?: string | null;
    };
  };
  legacyPath?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  namePt: string;
  nameEn?: string | null;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  /**
   * Entra no endereço em inglês (/en/…). Vazio, o inglês usa o slug português.
   */
  slugEn?: string | null;
  order?: number | null;
  claim?: {
    pt?: string | null;
    en?: string | null;
  };
  link?: {
    pt?: string | null;
    en?: string | null;
  };
  promise?: {
    pt?: string | null;
    en?: string | null;
  };
  includes?:
    | {
        item?: {
          pt?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  phases?:
    | {
        name?: {
          pt?: string | null;
          en?: string | null;
        };
        body?: {
          pt?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  cases?: (number | Project)[] | null;
  accent?: ('lavender' | 'chartreuse' | 'coral') | null;
  heroTitle?: {
    pt?: string | null;
    en?: string | null;
  };
  /**
   * Endereço do MP4 no armazenamento. Sem áudio, curto, e leve: um fundo de 7 segundos deve ficar abaixo de 1 MB (npm run video:prep encolhe-o).
   */
  heroVideo?: string | null;
  /**
   * O que se vê antes de o vídeo começar, e o que fica para quem pediu menos movimento.
   */
  heroPoster?: (number | null) | Media;
  /**
   * Quanto do ecrã ocupa a faixa de topo. Médio é o que se usa; alto é quase o ecrã todo.
   */
  heroHeight?: ('curto' | 'medio' | 'alto') | null;
  /**
   * Duas linhas: a afirmação, e a volta que ela dá.
   */
  statement?: {
    first?: {
      pt?: string | null;
      en?: string | null;
    };
    second?: {
      pt?: string | null;
      en?: string | null;
    };
  };
  areas?:
    | {
        title?: {
          pt?: string | null;
          en?: string | null;
        };
        body?: {
          pt?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  essayTitle?: {
    pt?: string | null;
    en?: string | null;
  };
  essay?:
    | {
        body?: {
          pt?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  essayImage?: (number | null) | Media;
  closing?: {
    question?: {
      pt?: string | null;
      en?: string | null;
    };
    answer?: {
      pt?: string | null;
      en?: string | null;
    };
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: number;
  titlePt: string;
  titleEn?: string | null;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  date: string;
  kind: 'noticia' | 'evento' | 'press';
  /**
   * Só para press: onde saiu.
   */
  outlet?: string | null;
  summary?: {
    pt?: string | null;
    en?: string | null;
  };
  /**
   * Se a notícia tem artigo no site, é para lá que a linha leva.
   */
  post?: (number | null) | Post;
  /**
   * Usado quando não há artigo: notícia na imprensa, inscrição num evento.
   */
  link?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients".
 */
export interface Client {
  id: number;
  name: string;
  sector:
    | 'financeiro'
    | 'saude'
    | 'bebidas'
    | 'consumo'
    | 'retalho'
    | 'industria'
    | 'construcao'
    | 'servicos'
    | 'arte'
    | 'eventos'
    | 'lazer'
    | 'tecnologia';
  logo?: (number | null) | Media;
  /**
   * Nome da galeria a que pertence.
   */
  gallery?: string | null;
  link?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos".
 */
export interface Logo {
  id: number;
  name?: string | null;
  gallery: string;
  image: number | Media;
  link?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  role?: {
    pt?: string | null;
    en?: string | null;
  };
  photo?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milestones".
 */
export interface Milestone {
  id: number;
  year: string;
  body?: {
    pt?: string | null;
    en?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Os briefings que entram pela página de contactos.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages".
 */
export interface Message {
  id: number;
  name: string;
  company?: string | null;
  email: string;
  message?: string | null;
  status?: ('nova' | 'respondida' | 'arquivada') | null;
  locale?: string | null;
  /**
   * Para quem responde: o que ficou combinado.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * As áreas de atuação da agência. É por aqui que as candidaturas se contam.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments".
 */
export interface Department {
  id: number;
  namePt: string;
  nameEn?: string | null;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  order?: number | null;
  /**
   * Quanto conta cada dimensão neste departamento, em pontos. A soma não tem de dar 100 — o cálculo normaliza. Num comercial ouvir pesa mais do que numa função técnica; num developer é o contrário.
   */
  weights?: {
    empathy?: number | null;
    attitude?: number | null;
    listening?: number | null;
    experience?: number | null;
    communication?: number | null;
    fit?: number | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * A tabela de funções. A vaga escolhe uma daqui, e o título dela pode ser escrito à medida.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-functions".
 */
export interface JobFunction {
  id: number;
  namePt: string;
  nameEn?: string | null;
  department: number | Department;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: number;
  titlePt: string;
  titleEn?: string | null;
  /**
   * Entra no URL. Mudar isto parte links que já existem.
   */
  slug: string;
  /**
   * Entra no endereço em inglês (/en/…). Vazio, o inglês usa o slug português.
   */
  slugEn?: string | null;
  /**
   * De onde vem o departamento, e por onde as candidaturas se agrupam.
   */
  function: number | JobFunction;
  status?: ('rascunho' | 'aberta' | 'fechada') | null;
  contract?: ('contrato' | 'estagio' | 'freelancer') | null;
  regime?: ('presencial' | 'hibrido' | 'remoto') | null;
  location?: string | null;
  seniority?: ('junior' | 'intermedio' | 'senior') | null;
  /**
   * Passada a data, a vaga sai da lista sozinha. Deixa vazio para ficar aberta sem prazo.
   */
  deadline?: string | null;
  intro?: {
    pt?: string | null;
    en?: string | null;
  };
  responsibilities?:
    | {
        item?: {
          pt?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  requirements?:
    | {
        item?: {
          pt?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  niceToHave?:
    | {
        item?: {
          pt?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        item?: {
          pt?: string | null;
          en?: string | null;
        };
        id?: string | null;
      }[]
    | null;
  closing?: {
    pt?: string | null;
    en?: string | null;
  };
  /**
   * As perguntas que só fazem sentido nesta vaga — ferramentas, canais, anos na função, valor/hora. Sem nada aqui, o formulário fica só com o essencial e o CV.
   */
  questions?:
    | {
        type: 'escolha' | 'varias' | 'curto' | 'longo' | 'numero';
        required?: boolean | null;
        label?: {
          pt?: string | null;
          en?: string | null;
        };
        /**
         * Uma linha por opção. Para deixar escrever à parte, acrescenta uma opção «Outra».
         */
        options?:
          | {
              value?: {
                pt?: string | null;
                en?: string | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  legacyPath?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  name: string;
  email: string;
  phone?: string | null;
  city?: string | null;
  country?: string | null;
  portfolio?: string | null;
  linkedin?: string | null;
  /**
   * Vazio quer dizer candidatura espontânea.
   */
  job?: (number | null) | Job;
  function?: (number | null) | JobFunction;
  /**
   * Quem se candidata espontaneamente pode marcar mais do que uma área.
   */
  department?: (number | Department)[] | null;
  /**
   * Uso interno, para saudações («Caro», «Cara»). Não se pergunta no formulário de candidatura — vem de quem escreve, ou do histórico.
   */
  gender?: ('feminino' | 'masculino' | 'outro' | 'nao-diz') | null;
  experienceYears?: ('nenhuma' | 'menos-de-um' | 'um-dois' | 'tres-cinco' | 'mais-de-cinco') | null;
  contractWanted?: ('contrato' | 'estagio' | 'freelancer') | null;
  cv?: (number | null) | Document;
  letter?: (number | null) | Document;
  /**
   * Consentimento separado do da candidatura, como tem de ser.
   */
  newsletterOptIn?: boolean | null;
  /**
   * As perguntas do formulário, como foram feitas, e o que a pessoa escreveu.
   */
  answers?:
    | {
        question?: string | null;
        answer?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Mudar o estado prepara o email para o candidato. Nada sai sem alguém carregar em enviar.
   */
  status?: ('nova' | 'em_avaliacao' | 'entrevista' | 'aprovado' | 'rejeitado') | null;
  evaluations?:
    | {
        interviewer?: (number | null) | User;
        date?: string | null;
        /**
         * Percebeu o outro lado — do cliente, do colega. 3 reconhece que existe; 5 descreve o que o outro sentia e o que fez com isso.
         */
        empathy?: ('1' | '2' | '3' | '4' | '5') | null;
        empathyNote?: string | null;
        /**
         * 3 fez o que lhe pediram; 5 viu o problema, avançou sem ninguém pedir, e assume o que correu mal.
         */
        attitude?: ('1' | '2' | '3' | '4' | '5') | null;
        attitudeNote?: string | null;
        /**
         * 3 responde ao que foi perguntado; 5 devolve o que ouviu por outras palavras e pergunta o que falta.
         */
        listening?: ('1' | '2' | '3' | '4' | '5') | null;
        listeningNote?: string | null;
        /**
         * Conta o que fez, não onde esteve. 3 dá um exemplo próprio; 5 dá exemplos com números e diz o que faria diferente.
         */
        experience?: ('1' | '2' | '3' | '4' | '5') | null;
        experienceNote?: string | null;
        /**
         * 3 explica-se; 5 adapta ao interlocutor e torna simples o que é complexo.
         */
        communication?: ('1' | '2' | '3' | '4' | '5') | null;
        communicationNote?: string | null;
        /**
         * A competência específica da função. 3 faz o essencial; 5 está à frente do que a vaga pede.
         */
        fit?: ('1' | '2' | '3' | '4' | '5') | null;
        fitNote?: string | null;
        /**
         * Separada da nota de propósito: uma média de 4 pode ainda assim ser um não, e ao contrário também.
         */
        recommendation?: ('avancar' | 'reservas' | 'nao') | null;
        notes?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Média ponderada, de 1 a 5.
   */
  rating?: number | null;
  /**
   * Diferença entre a ficha mais alta e a mais baixa. Acima de 1,5 vale mais conversar do que somar.
   */
  spread?: number | null;
  /**
   * Porque é que se decidiu assim. Fica no processo.
   */
  decisionNote?: string | null;
  /**
   * O registo do Gravity Forms de onde esta candidatura veio. É o que impede importar duas vezes.
   */
  legacyId?: string | null;
  consentAt?: string | null;
  source?: string | null;
  /**
   * Doze meses para as espontâneas, seis meses depois de a vaga fechar. Um trabalho diário apaga o que passou desta data.
   */
  retentionUntil?: string | null;
  emails?:
    | {
        kind?: string | null;
        sentAt?: string | null;
        sentBy?: (number | null) | User;
        to?: string | null;
        subject?: string | null;
        body?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents".
 */
export interface Document {
  id: number;
  note?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  /**
   * Administração vê tudo. Recrutamento é o único perfil que vê as candidaturas.
   */
  roles?: ('admin' | 'editorial' | 'recrutamento')[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'news';
        value: number | News;
      } | null)
    | ({
        relationTo: 'clients';
        value: number | Client;
      } | null)
    | ({
        relationTo: 'logos';
        value: number | Logo;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'milestones';
        value: number | Milestone;
      } | null)
    | ({
        relationTo: 'messages';
        value: number | Message;
      } | null)
    | ({
        relationTo: 'departments';
        value: number | Department;
      } | null)
    | ({
        relationTo: 'job-functions';
        value: number | JobFunction;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'applications';
        value: number | Application;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'documents';
        value: number | Document;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  key?: T;
  images?: T;
  entries?:
    | T
    | {
        key?: T;
        pt?: T;
        en?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  titlePt?: T;
  titleEn?: T;
  slug?: T;
  slugEn?: T;
  date?: T;
  author?: T;
  readingMinutes?: T;
  category?: T;
  excerpt?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  cover?: T;
  body?: T;
  bodyEn?: T;
  lang?: T;
  legacyPath?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  titlePt?: T;
  titleEn?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  client?: T;
  slug?: T;
  slugEn?: T;
  year?: T;
  date?: T;
  order?: T;
  written?: T;
  subtitle?: T;
  disciplines?: T;
  title?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  summary?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  team?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  cover?: T;
  story?:
    | T
    | {
        text?:
          | T
          | {
              heading?: T;
              level?: T;
              body?: T;
              id?: T;
              blockName?: T;
            };
        image?:
          | T
          | {
              image?: T;
              id?: T;
              blockName?: T;
            };
        gallery?:
          | T
          | {
              images?: T;
              id?: T;
              blockName?: T;
            };
        video?:
          | T
          | {
              mp4?: T;
              webm?: T;
              poster?: T;
              portrait?: T;
              id?: T;
              blockName?: T;
            };
        embed?:
          | T
          | {
              url?: T;
              id?: T;
              blockName?: T;
            };
        link?:
          | T
          | {
              label?: T;
              href?: T;
              id?: T;
              blockName?: T;
            };
      };
  numbersValidated?: T;
  headline?:
    | T
    | {
        value?: T;
        label?:
          | T
          | {
              pt?: T;
              en?: T;
            };
      };
  kpis?:
    | T
    | {
        value?: T;
        label?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        id?: T;
      };
  quote?:
    | T
    | {
        text?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        author?: T;
        role?:
          | T
          | {
              pt?: T;
              en?: T;
            };
      };
  legacyPath?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  namePt?: T;
  nameEn?: T;
  slug?: T;
  slugEn?: T;
  order?: T;
  claim?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  link?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  promise?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  includes?:
    | T
    | {
        item?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        id?: T;
      };
  phases?:
    | T
    | {
        name?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        body?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        id?: T;
      };
  cases?: T;
  accent?: T;
  heroTitle?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  heroVideo?: T;
  heroPoster?: T;
  heroHeight?: T;
  statement?:
    | T
    | {
        first?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        second?:
          | T
          | {
              pt?: T;
              en?: T;
            };
      };
  areas?:
    | T
    | {
        title?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        body?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        id?: T;
      };
  essayTitle?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  essay?:
    | T
    | {
        body?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        id?: T;
      };
  essayImage?: T;
  closing?:
    | T
    | {
        question?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        answer?:
          | T
          | {
              pt?: T;
              en?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  titlePt?: T;
  titleEn?: T;
  slug?: T;
  date?: T;
  kind?: T;
  outlet?: T;
  summary?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  post?: T;
  link?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clients_select".
 */
export interface ClientsSelect<T extends boolean = true> {
  name?: T;
  sector?: T;
  logo?: T;
  gallery?: T;
  link?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "logos_select".
 */
export interface LogosSelect<T extends boolean = true> {
  name?: T;
  gallery?: T;
  image?: T;
  link?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  role?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  photo?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "milestones_select".
 */
export interface MilestonesSelect<T extends boolean = true> {
  year?: T;
  body?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "messages_select".
 */
export interface MessagesSelect<T extends boolean = true> {
  name?: T;
  company?: T;
  email?: T;
  message?: T;
  status?: T;
  locale?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "departments_select".
 */
export interface DepartmentsSelect<T extends boolean = true> {
  namePt?: T;
  nameEn?: T;
  slug?: T;
  order?: T;
  weights?:
    | T
    | {
        empathy?: T;
        attitude?: T;
        listening?: T;
        experience?: T;
        communication?: T;
        fit?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-functions_select".
 */
export interface JobFunctionsSelect<T extends boolean = true> {
  namePt?: T;
  nameEn?: T;
  department?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  titlePt?: T;
  titleEn?: T;
  slug?: T;
  slugEn?: T;
  function?: T;
  status?: T;
  contract?: T;
  regime?: T;
  location?: T;
  seniority?: T;
  deadline?: T;
  intro?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  responsibilities?:
    | T
    | {
        item?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        id?: T;
      };
  requirements?:
    | T
    | {
        item?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        id?: T;
      };
  niceToHave?:
    | T
    | {
        item?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        id?: T;
      };
  benefits?:
    | T
    | {
        item?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        id?: T;
      };
  closing?:
    | T
    | {
        pt?: T;
        en?: T;
      };
  questions?:
    | T
    | {
        type?: T;
        required?: T;
        label?:
          | T
          | {
              pt?: T;
              en?: T;
            };
        options?:
          | T
          | {
              value?:
                | T
                | {
                    pt?: T;
                    en?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  legacyPath?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  city?: T;
  country?: T;
  portfolio?: T;
  linkedin?: T;
  job?: T;
  function?: T;
  department?: T;
  gender?: T;
  experienceYears?: T;
  contractWanted?: T;
  cv?: T;
  letter?: T;
  newsletterOptIn?: T;
  answers?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  status?: T;
  evaluations?:
    | T
    | {
        interviewer?: T;
        date?: T;
        empathy?: T;
        empathyNote?: T;
        attitude?: T;
        attitudeNote?: T;
        listening?: T;
        listeningNote?: T;
        experience?: T;
        experienceNote?: T;
        communication?: T;
        communicationNote?: T;
        fit?: T;
        fitNote?: T;
        recommendation?: T;
        notes?: T;
        id?: T;
      };
  rating?: T;
  spread?: T;
  decisionNote?: T;
  legacyId?: T;
  consentAt?: T;
  source?: T;
  retentionUntil?: T;
  emails?:
    | T
    | {
        kind?: T;
        sentAt?: T;
        sentBy?: T;
        to?: T;
        subject?: T;
        body?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  title?: T;
  alt?: T;
  caption?: T;
  legacyUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        wide?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "documents_select".
 */
export interface DocumentsSelect<T extends boolean = true> {
  note?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}