import type { Localized } from "./types";

/**
 * A página da Imunidade Algorítmica.
 *
 * O texto vive aqui e não nas traduções da interface: são dois mil e tantos
 * caracteres de argumento, e um ficheiro de etiquetas não é sítio para prosa.
 * O português é o original — o termo foi cunhado em português — e o inglês é
 * tradução.
 *
 * Cada camada tem um «critério de saída», e é isso que separa isto de um
 * manifesto: uma condição verificável para se poder dizer que a camada está
 * feita. É o dispositivo mais forte do texto, e por isso tem desenho próprio.
 */

export type Camada = {
  numero: string;
  nome: Localized;
  corpo: Localized;
  criterio: Localized;
  /** A cor da paleta que marca esta camada. */
  cor: "red" | "coral" | "lavender" | "chartreuse" | "paper";
};

export type Pergunta = { pergunta: Localized; resposta: Localized };

export const imunidade = {
  eyebrow: { pt: "Conceito", en: "Concept" },
  titulo: { pt: "Imunidade Algorítmica", en: "Algorithmic Immunity" },
  claim: {
    pt: "Quando uma marca se torna incontornável nas respostas de pesquisa e de inteligência artificial.",
    en: "When a brand becomes unavoidable in search results and in what artificial intelligence answers.",
  },
  descricao: {
    pt: "Imunidade Algorítmica é o estado atingido por uma marca quando se torna incontornável nos resultados de pesquisa e nas respostas geradas pela inteligência artificial. Um conceito cunhado por Gonçalo Malho Rodrigues, fundador da Jelly.",
    en: "Algorithmic Immunity is the state a brand reaches when it becomes unavoidable in search results and in answers generated by artificial intelligence. A concept coined by Gonçalo Malho Rodrigues, founder of Jelly.",
  },

  definicao: {
    titulo: { pt: "O que é Imunidade Algorítmica?", en: "What is Algorithmic Immunity?" },
    paragrafos: [
      {
        pt: "Imunidade Algorítmica é o estado atingido por uma marca quando se torna incontornável nos resultados de pesquisa e nas respostas geradas pela inteligência artificial. Quando alguém pergunta sobre o seu universo e essa marca surge como resposta e recomendação. Não por um acaso, mas porque o sistema a reconhece como referência no tópico.",
        en: "Algorithmic Immunity is the state a brand reaches when it becomes unavoidable in search results and in answers generated by artificial intelligence. When someone asks about its world and that brand comes up as the answer and the recommendation. Not by chance, but because the system recognises it as the reference on the topic.",
      },
      {
        pt: "Por isso, convém já desfazer um equívoco. Imunidade Algorítmica não se conquista com uma palavra-chave, com um esquema de SEO ou com um atalho técnico. Conquista-se de uma maneira mais lenta e mais antiga: por fazer bem feito, durante muito tempo, aquilo que se faz.",
        en: "So let us clear up a misunderstanding right away. Algorithmic Immunity is not won with a keyword, an SEO scheme or a technical shortcut. It is won in a slower and older way: by doing what you do well, for a long time.",
      },
    ],
    tese: {
      pt: "O algoritmo não cria a autoridade de uma marca. Ele lê uma autoridade que já existe lá fora, no mundo real, e devolve-a a quem pergunta.",
      en: "The algorithm does not create a brand's authority. It reads an authority that already exists out there, in the real world, and hands it back to whoever asks.",
    },
  },

  autor: {
    rotulo: { pt: "O termo", en: "The term" },
    texto: {
      pt: "cunhou o termo «Imunidade Algorítmica» para dar nome à filosofia que aplica há quase três décadas: uma estratégia de marca de longo prazo, assente em táticas intemporais e, por isso mesmo, imune às variações de algoritmo.",
      en: "coined the term “Algorithmic Immunity” to name the philosophy he has applied for almost three decades: a long-term brand strategy, built on timeless tactics and, for that very reason, immune to algorithm changes.",
    },
  },

  camadasIntro: {
    titulo: { pt: "Constrói-se por camadas, e a técnica é a última", en: "It is built in layers, and the technique comes last" },
    paragrafos: [
      {
        pt: "A autoridade não nasce de uma estratégia de conteúdo. Nasce do trabalho bem feito que deixa rasto.",
        en: "Authority does not come from a content strategy. It comes from work done well that leaves a trail.",
      },
      {
        pt: "A qualidade consistente do produto que a marca entrega, a lealdade dos clientes, as parcerias bem-sucedidas, os eventos. As pessoas falam, recomendam, citam. E é esse rasto, deixado por outros, que a máquina valoriza. Tudo o que se faz na terra é, mais cedo ou mais tarde, lido no digital.",
        en: "The consistent quality of what the brand delivers, the loyalty of its clients, the partnerships that worked, the events. People talk, recommend, cite. And it is that trail, left by others, that the machine values. Everything done on the ground is, sooner or later, read in the digital.",
      },
    ],
  },

  tecnica: {
    titulo: { pt: "Sobre a técnica (SEO e GEO)", en: "On the technique (SEO and GEO)" },
    paragrafos: [
      {
        pt: "A componente técnica conta, claro, mas o seu lugar é no fim. SEO, GEO, dados estruturados: servem para que a autoridade já construída seja lida sem ruído e o sinal amplificado.",
        en: "The technical side counts, of course, but its place is at the end. SEO, GEO, structured data: they exist so that the authority already built is read without noise and the signal amplified.",
      },
      {
        pt: "A técnica amplifica o que é real, deixando a marca sujeita ao próprio desempenho. Primeiro a substância, depois a técnica que a torna legível.",
        en: "Technique amplifies what is real, leaving the brand answerable to its own performance. Substance first, then the technique that makes it legible.",
      },
    ],
  },

  contraste: {
    titulo: {
      pt: "O que distingue Imunidade Algorítmica de SEO tradicional",
      en: "What sets Algorithmic Immunity apart from traditional SEO",
    },
    velho: {
      rotulo: { pt: "SEO tradicional", en: "Traditional SEO" },
      texto: {
        pt: "Uma corrida atrás do algoritmo. Sai uma atualização, ajusta-se a estratégia. Muda um fator de ranking, refaz-se o trabalho.",
        en: "A race behind the algorithm. An update lands, the strategy is adjusted. A ranking factor changes, the work is redone.",
      },
    },
    novo: {
      rotulo: { pt: "Imunidade Algorítmica", en: "Algorithmic Immunity" },
      texto: {
        pt: "Inverte essa relação. A autoridade conquistada pela marca torna-a incontornável, apesar das mudanças algorítmicas ou até das revoluções tecnológicas — como é o caso da maior de todas: a IA.",
        en: "Inverts that relationship. The authority a brand has won makes it unavoidable, despite algorithm changes or even technological revolutions — the biggest of them all being AI.",
      },
    },
  },

  comoIntro: {
    titulo: { pt: "Como se constrói", en: "How it is built" },
    texto: {
      pt: "Imunidade Algorítmica não se compra nem se ativa num trimestre. Constrói-se, de dentro para fora.",
      en: "Algorithmic Immunity is not bought, and it does not switch on in a quarter. It is built, from the inside out.",
    },
    criterioRotulo: { pt: "Critério de saída", en: "Exit criterion" },
  },

  camadas: [
    {
      numero: "01",
      cor: "red",
      nome: { pt: "Substância", en: "Substance" },
      corpo: {
        pt: "Ganhar o sinal na terra. Produto, serviço e assistência com qualidade real, e um posicionamento inequívoco: ser a resposta óbvia a uma pergunta específica. Sem isto, tudo o resto é ruído fabricado.",
        en: "Earn the signal on the ground. Product, service and support with real quality, and an unambiguous position: being the obvious answer to a specific question. Without this, everything else is manufactured noise.",
      },
      criterio: {
        pt: "Clientes reais a recomendar-te espontaneamente.",
        en: "Real clients recommending you unprompted.",
      },
    },
    {
      numero: "02",
      cor: "coral",
      nome: { pt: "Registo", en: "Record" },
      corpo: {
        pt: "Capturar o sinal. Transformar a experiência vivida em prova pública e sistemática: reviews como processo e não como acaso, casos documentados, imprensa e citações de terceiros.",
        en: "Capture the signal. Turn lived experience into public, systematic proof: reviews as a process rather than an accident, documented cases, press and third-party citations.",
      },
      criterio: {
        pt: "A reputação existe por escrito, fora dos canais proprietários, em fontes que a marca não controla.",
        en: "The reputation exists in writing, outside owned channels, in sources the brand does not control.",
      },
    },
    {
      numero: "03",
      cor: "lavender",
      nome: { pt: "Coerência", en: "Coherence" },
      corpo: {
        pt: "Limpar o ruído. Consistência de entidade em todos os pontos onde a marca é lida: mesmo nome, mesma promessa, mesma linguagem, dados alinhados no site, nos diretórios, nas redes e na imprensa.",
        en: "Clear the noise. Entity consistency everywhere the brand is read: same name, same promise, same language, aligned data across the site, directories, social and press.",
      },
      criterio: {
        pt: "Não existe informação contraditória sobre a marca em lado nenhum.",
        en: "There is no contradictory information about the brand anywhere.",
      },
    },
    {
      numero: "04",
      cor: "chartreuse",
      nome: { pt: "Amplificação", en: "Amplification" },
      corpo: {
        pt: "Fazer o sinal chegar à máquina. GEO e AEO: dados estruturados, conteúdo citável, presença nas fontes que os motores de resposta usam como referência.",
        en: "Get the signal to the machine. GEO and AEO: structured data, quotable content, presence in the sources answer engines use as reference.",
      },
      criterio: {
        pt: "A IA cita a marca quando alguém pergunta pela sua categoria.",
        en: "AI cites the brand when someone asks about its category.",
      },
    },
    {
      numero: "05",
      cor: "paper",
      nome: { pt: "Imunidade", en: "Immunity" },
      corpo: {
        pt: "O efeito composto. Distribuição própria — email, comunidade, marca pessoal —, monitorização contínua de como a IA te representa, e reinvestimento no ciclo. É aqui que a marca deixa de depender de qualquer algoritmo em particular.",
        en: "The compound effect. Owned distribution — email, community, personal brand —, continuous monitoring of how AI represents you, and reinvestment in the cycle. This is where the brand stops depending on any particular algorithm.",
      },
      criterio: {
        pt: "Não há. É regime permanente.",
        en: "There is none. It is a permanent state.",
      },
    },
  ] satisfies Camada[],

  faqTitulo: { pt: "Perguntas que nos fazem", en: "Questions we get asked" },

  faq: [
    {
      pergunta: { pt: "A Imunidade Algorítmica é o mesmo que SEO ou GEO?", en: "Is Algorithmic Immunity the same as SEO or GEO?" },
      resposta: {
        pt: "Não. SEO e GEO são a camada técnica que ajuda a máquina a ler corretamente uma marca. A Imunidade Algorítmica é o resultado de fundo, alcançado sobretudo através de reputação e trabalho bem feito, para os quais a técnica é o último elo e não o primeiro.",
        en: "No. SEO and GEO are the technical layer that helps the machine read a brand correctly. Algorithmic Immunity is the underlying result, reached mostly through reputation and work done well, for which technique is the last link and not the first.",
      },
    },
    {
      pergunta: { pt: "Quanto tempo demora a construir Imunidade Algorítmica?", en: "How long does it take to build Algorithmic Immunity?" },
      resposta: {
        pt: "Não é imediato. Depende da reputação acumulada e da consistência da marca ao longo de meses e anos. É precisamente por não ter atalho que se torna uma vantagem competitiva difícil de copiar.",
        en: "It is not immediate. It depends on accumulated reputation and on the brand's consistency over months and years. It is precisely because there is no shortcut that it becomes a competitive advantage that is hard to copy.",
      },
    },
    {
      pergunta: { pt: "Aplica-se a marcas pessoais ou a empresas?", en: "Does it apply to personal brands or to companies?" },
      resposta: {
        pt: "Aos dois, e pela mesma lógica. Uma marca pessoal e uma empresa são ambas entidades que a máquina tem de reconhecer, ligar a um território e citar. A diferença está na escala e nas fontes do rasto, não no princípio.",
        en: "To both, by the same logic. A personal brand and a company are both entities the machine has to recognise, tie to a territory and cite. The difference is in the scale and in the sources of the trail, not in the principle.",
      },
    },
    {
      pergunta: { pt: "Isto é a mesma coisa que ter boa reputação online?", en: "Is this the same as having a good online reputation?" },
      resposta: {
        pt: "É a consequência disso, lida por um novo intermediário. A reputação sempre existiu; o que mudou é que agora há um modelo a interpretá-la e a devolvê-la em nome da marca. Boa reputação sem legibilidade técnica fica invisível; legibilidade técnica sem reputação não tem o que mostrar.",
        en: "It is the consequence of it, read by a new intermediary. Reputation always existed; what changed is that there is now a model interpreting it and handing it back on the brand's behalf. Good reputation without technical legibility stays invisible; technical legibility without reputation has nothing to show.",
      },
    },
    {
      pergunta: { pt: "Por onde começo se a minha marca ainda não tem presença nenhuma?", en: "Where do I start if my brand has no presence at all?" },
      resposta: {
        pt: "Pela substância e pela coerência, nunca pela técnica. Primeiro, ter algo que mereça ser dito e um ponto de vista próprio. Depois, apresentar-se de forma consistente em todo o lado. Só quando isto existe é que faz sentido investir em SEO e GEO.",
        en: "With substance and coherence, never with technique. First, have something worth saying and a point of view of your own. Then present yourself consistently everywhere. Only once this exists does it make sense to invest in SEO and GEO.",
      },
    },
    {
      pergunta: { pt: "Como sei se estou a ganhar Imunidade Algorítmica? Consegue medir-se?", en: "How do I know if I am gaining Algorithmic Immunity? Can it be measured?" },
      resposta: {
        pt: "Sim, de forma imperfeita, mas útil. Pergunta-se regularmente às próprias IA sobre o teu tema e vê-se se a marca aparece, com que frequência e se é bem caracterizada. Acompanha-se a evolução ao longo do tempo, não num único dia, pois as respostas oscilam.",
        en: "Yes, imperfectly, but usefully. You ask the AI systems themselves about your topic on a regular basis and see whether the brand shows up, how often, and whether it is well characterised. You track the trend over time, not on a single day, because answers fluctuate.",
      },
    },
    {
      pergunta: { pt: "Preciso de produzir muito conteúdo para isto funcionar?", en: "Do I need to produce a lot of content for this to work?" },
      resposta: {
        pt: "Não é volume, é densidade e credibilidade. Um conteúdo substancial e citável, referido por terceiros, vale mais do que dezenas de artigos que ninguém menciona. A máquina premeia a substância e ignora o ruído.",
        en: "It is not volume, it is density and credibility. One substantial, quotable piece referenced by others is worth more than dozens of articles nobody mentions. The machine rewards substance and ignores noise.",
      },
    },
    {
      pergunta: { pt: "Não é isto apenas SEO com outro nome para vender mais caro?", en: "Is this just SEO under another name, to sell at a higher price?" },
      resposta: {
        pt: "Não, e a diferença é a ordem. SEO e GEO são a camada técnica, o último elo. A Imunidade Algorítmica é o resultado de fundo, construído sobre reputação real. Quem trata a técnica como o princípio, e não como o fim, otimiza o vazio.",
        en: "No, and the difference is the order. SEO and GEO are the technical layer, the last link. Algorithmic Immunity is the underlying result, built on real reputation. Treat technique as the beginning rather than the end and you are optimising a void.",
      },
    },
    {
      pergunta: { pt: "E se eu simplesmente pagar para aparecer nas respostas da IA?", en: "What if I simply pay to appear in AI answers?" },
      resposta: {
        pt: "Não é assim que funciona, e é essa a boa notícia. Não há um botão nem um espaço publicitário que garanta a citação orgânica de uma marca como referência. Precisamente por não se comprar é que é um ativo defensável.",
        en: "That is not how it works, and that is the good news. There is no button and no ad slot that guarantees a brand is organically cited as a reference. Precisely because it cannot be bought, it is a defensible asset.",
      },
    },
    {
      pergunta: { pt: "E se a IA disser coisas erradas ou desatualizadas sobre a minha marca?", en: "What if AI says wrong or outdated things about my brand?" },
      resposta: {
        pt: "É um risco real e faz parte do trabalho geri-lo. Caracterizações erradas corrigem-se alimentando a máquina com sinais corretos e consistentes nas fontes que ela lê. Ignorar é que é perigoso, porque a versão errada consolida-se.",
        en: "It is a real risk and managing it is part of the work. Wrong characterisations are corrected by feeding the machine correct, consistent signals in the sources it reads. Ignoring it is the dangerous option, because the wrong version settles in.",
      },
    },
  ] satisfies Pergunta[],

  fecho: {
    titulo: {
      pt: "Fez sentido? Vamos construir a Imunidade da sua marca.",
      en: "Did this make sense? Let's build your brand's Immunity.",
    },
    cta: { pt: "Vamos conversar", en: "Let's talk" },
  },
} as const;
